// import getCurrentUser from "./actions/getCurrentUser";
// import getMovie from "./actions/getMovie";
// import getAllMovies from "./actions/getAllMovies";
// import getFavoriteMovie from "./actions/getFavoriteMovie";

// import Container from "./components/Container";
// import Navbar from "./components/navbar/Navbar";
// import Billboard from "./components/Billboard";
// import MovieList from "./components/MovieList";
// import InfoModal from "./components/InfoModal";

// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const currentuser = await getCurrentUser();
//   const movie = await getMovie();
//   const allMovies = await getAllMovies();
//   const favoriteMovie = await getFavoriteMovie();
//   return (
//     <html lang="en">
//       <body>
//         <Navbar currentuser={currentuser} />
//         <Billboard movie={movie} allMovies={allMovies} />
//         <InfoModal movie={movie} currentuser={currentuser} />
//         <div className="pb-40">
//           <MovieList
//             data={allMovies}
//             title="Trending Now"
//             currentuser={currentuser}
//           />
//           <MovieList
//             data={favoriteMovie}
//             title="My List"
//             currentuser={currentuser}
//           />
//         </div>
//         {children}
//       </body>
//     </html>
//   );
// }

import getCurrentUser from "./actions/getCurrentUser";

import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
